### ISSUE TITLE
 Cannot run program "/usr/bin/pygmentize": error=2

### ISSUE THREAD

**Issue by gzmask** [algernon/madness#2]
After I ran: lein run -m madness.core
I got:

Exception in thread "main" java.io.IOException: Cannot run program "/usr/bin/pygmentize": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041)
    at conch.core$proc.doInvoke(core.clj:30)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:603)
    at conch.sh$run_command.invoke(sh.clj:151)
    at conch.sh$execute.doInvoke(sh.clj:180)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.core$apply.invoke(core.clj:603)
    at madness.utils$pygmentize$pygmentize__2371.doInvoke(utils.clj:199)
    at clojure.lang.RestFn.invoke(RestFn.java:457)
    at madness.utils$pygmentize.invoke(utils.clj:201)
    at madness.utils$pygmentize_node.invoke(utils.clj:210)
    at net.cgrand.enlive_html$transform_loc.invoke(enlive_html.clj:414)
    at net.cgrand.enlive_html$transform_loc$fn__423.invoke(enlive_html.clj:410)
    at net.cgrand.enlive_html$mapknit$fn__135.invoke(enlive_html.clj:24)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.Cons.next(Cons.java:39)
    at clojure.lang.RT.next(RT.java:587)
    at clojure.core$next.invoke(core.clj:64)
    at clojure.core$nthnext.invoke(core.clj:2754)
    at clojure.zip$right.invoke(zip.clj:153)
    at net.cgrand.enlive_html$iterate_while$fn__138.invoke(enlive_html.clj:29)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.RT.seq(RT.java:473)
    at clojure.core$seq.invoke(core.clj:133)
    at net.cgrand.enlive_html$mapknit$fn__135.invoke(enlive_html.clj:23)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.Cons.next(Cons.java:39)
    at clojure.lang.RT.next(RT.java:587)
    at clojure.core$next.invoke(core.clj:64)
    at clojure.core$nthnext.invoke(core.clj:2754)
    at clojure.zip$right.invoke(zip.clj:153)
    at net.cgrand.enlive_html$iterate_while$fn__138.invoke(enlive_html.clj:29)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.RT.seq(RT.java:473)
    at clojure.core$seq.invoke(core.clj:133)
    at net.cgrand.enlive_html$mapknit$fn__135.invoke(enlive_html.clj:23)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.Cons.next(Cons.java:39)
    at clojure.lang.RT.next(RT.java:587)
    at clojure.core$next.invoke(core.clj:64)
    at clojure.core$nthnext.invoke(core.clj:2754)
    at clojure.zip$right.invoke(zip.clj:153)
    at net.cgrand.enlive_html$iterate_while$fn__138.invoke(enlive_html.clj:29)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.RT.seq(RT.java:473)
    at clojure.core$seq.invoke(core.clj:133)
    at net.cgrand.enlive_html$mapknit$fn__135.invoke(enlive_html.clj:23)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.Cons.next(Cons.java:39)
    at clojure.lang.RT.next(RT.java:587)
    at clojure.core$next.invoke(core.clj:64)
    at clojure.core$nthnext.invoke(core.clj:2754)
    at clojure.zip$right.invoke(zip.clj:153)
    at net.cgrand.enlive_html$iterate_while$fn__138.invoke(enlive_html.clj:29)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.RT.seq(RT.java:473)
    at clojure.core$seq.invoke(core.clj:133)
    at net.cgrand.enlive_html$mapknit$fn__135.invoke(enlive_html.clj:23)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.RT.seq(RT.java:473)
    at clojure.core$seq.invoke(core.clj:133)
    at net.cgrand.enlive_html$mapknit$fn__135.invoke(enlive_html.clj:23)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.Cons.next(Cons.java:39)
    at clojure.lang.RT.next(RT.java:587)
    at clojure.core$next.invoke(core.clj:64)
    at clojure.core$str$fn__3777.invoke(core.clj:501)
    at clojure.core$str.doInvoke(core.clj:503)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.core$apply.invoke(core.clj:601)
    at madness.render$render_to_file.invoke(render.clj:36)
    at madness.render$eval3047$fn__3048.invoke(render.clj:210)
    at clojure.lang.MultiFn.invoke(MultiFn.java:172)
    at clojure.lang.AFn.applyToHelper(AFn.java:167)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.core$apply.invoke(core.clj:605)
    at clojure.core$partial$fn__4072.doInvoke(core.clj:2345)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$map$fn__4087.invoke(core.clj:2434)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.RT.seq(RT.java:473)
    at clojure.core$seq.invoke(core.clj:133)
    at clojure.core$dorun.invoke(core.clj:2725)
    at madness.render$eval3051$fn__3052.invoke(render.clj:214)
    at clojure.lang.MultiFn.invoke(MultiFn.java:163)
    at clojure.core$map$fn__4087.invoke(core.clj:2434)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.Cons.next(Cons.java:39)
    at clojure.lang.RT.next(RT.java:587)
    at clojure.core$next.invoke(core.clj:64)
    at clojure.core$dorun.invoke(core.clj:2726)
    at madness.core$_main.doInvoke(core.clj:41)
    at clojure.lang.RestFn.invoke(RestFn.java:703)
    at madness.core$_main.invoke(core.clj:39)
    at clojure.lang.Var.invoke(Var.java:411)
    at user$eval5$fn__7.invoke(form-init5003128797222942626.clj:1)
    at user$eval5.invoke(form-init5003128797222942626.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6511)
    at clojure.lang.Compiler.eval(Compiler.java:6501)
    at clojure.lang.Compiler.load(Compiler.java:6952)
    at clojure.lang.Compiler.loadFile(Compiler.java:6912)
    at clojure.main$load_script.invoke(main.clj:283)
    at clojure.main$init_opt.invoke(main.clj:288)
    at clojure.main$initialize.invoke(main.clj:316)
    at clojure.main$null_opt.invoke(main.clj:349)
    at clojure.main$main.doInvoke(main.clj:427)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:135)
    at java.lang.ProcessImpl.start(ProcessImpl.java:130)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1022)
    ... 123 more

**Comment by algernon** [comment]
It is now possible to disable syntax highlighting, and `pygmentize` is not required then.
